// Generated by gencpp from file lane_follower/MotorPWM_msg.msg
// DO NOT EDIT!


#ifndef LANE_FOLLOWER_MESSAGE_MOTORPWM_MSG_H
#define LANE_FOLLOWER_MESSAGE_MOTORPWM_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lane_follower
{
template <class ContainerAllocator>
struct MotorPWM_msg_
{
  typedef MotorPWM_msg_<ContainerAllocator> Type;

  MotorPWM_msg_()
    : left_pwm(0)
    , right_pwm(0)  {
    }
  MotorPWM_msg_(const ContainerAllocator& _alloc)
    : left_pwm(0)
    , right_pwm(0)  {
  (void)_alloc;
    }



   typedef int16_t _left_pwm_type;
  _left_pwm_type left_pwm;

   typedef int16_t _right_pwm_type;
  _right_pwm_type right_pwm;





  typedef boost::shared_ptr< ::lane_follower::MotorPWM_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lane_follower::MotorPWM_msg_<ContainerAllocator> const> ConstPtr;

}; // struct MotorPWM_msg_

typedef ::lane_follower::MotorPWM_msg_<std::allocator<void> > MotorPWM_msg;

typedef boost::shared_ptr< ::lane_follower::MotorPWM_msg > MotorPWM_msgPtr;
typedef boost::shared_ptr< ::lane_follower::MotorPWM_msg const> MotorPWM_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lane_follower::MotorPWM_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lane_follower::MotorPWM_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lane_follower::MotorPWM_msg_<ContainerAllocator1> & lhs, const ::lane_follower::MotorPWM_msg_<ContainerAllocator2> & rhs)
{
  return lhs.left_pwm == rhs.left_pwm &&
    lhs.right_pwm == rhs.right_pwm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lane_follower::MotorPWM_msg_<ContainerAllocator1> & lhs, const ::lane_follower::MotorPWM_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lane_follower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lane_follower::MotorPWM_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lane_follower::MotorPWM_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lane_follower::MotorPWM_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lane_follower::MotorPWM_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lane_follower::MotorPWM_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lane_follower::MotorPWM_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lane_follower::MotorPWM_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1bbcb2731ff8485f26f1b76809762437";
  }

  static const char* value(const ::lane_follower::MotorPWM_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1bbcb2731ff8485fULL;
  static const uint64_t static_value2 = 0x26f1b76809762437ULL;
};

template<class ContainerAllocator>
struct DataType< ::lane_follower::MotorPWM_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lane_follower/MotorPWM_msg";
  }

  static const char* value(const ::lane_follower::MotorPWM_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lane_follower::MotorPWM_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 left_pwm\n"
"int16 right_pwm\n"
;
  }

  static const char* value(const ::lane_follower::MotorPWM_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lane_follower::MotorPWM_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_pwm);
      stream.next(m.right_pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorPWM_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lane_follower::MotorPWM_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lane_follower::MotorPWM_msg_<ContainerAllocator>& v)
  {
    s << indent << "left_pwm: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left_pwm);
    s << indent << "right_pwm: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right_pwm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LANE_FOLLOWER_MESSAGE_MOTORPWM_MSG_H
