get_property(ENABLED_LANGUAGES_LIST GLOBAL PROPERTY ENABLED_LANGUAGES)
list(FIND ENABLED_LANGUAGES_LIST "CXX" _cxx_index)
if(NOT (APPLE OR WIN32 OR MINGW OR ANDROID) AND "${_cxx_index}" GREATER -1)
  if(${CMAKE_VERSION} VERSION_LESS 2.8.4)
    set(RT_LIBRARY rt CACHE FILEPATH "Hacked find of rt for cmake < 2.8.4")
  else()
    if(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
      set(RT_LIBRARY "/usr/lib/aarch64-linux-gnu/librt.so" CACHE FILEPATH "RT Library for aarch64")
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
      find_library(RT_LIBRARY rt)
    else()
      find_library(RT_LIBRARY rt)
    endif()
    assert_file_exists(${RT_LIBRARY} "RT Library")
  endif()
  #message(STATUS "RT_LIBRARY: ${RT_LIBRARY}")
endif()